import {ProjectRepository} from '../persistence/repository.js';import {createProject,touch} from '../project/project.js';import {createFile,createDirectory,removeEntry,renameEntry,parentPath} from '../filesystem/fileSystem.js';import {fromTemplate,templates} from '../templates/templates.js';import {ExecutionService} from '../execution/executionService.js';import {exportProject,importProject} from '../project/archive.js';import {mergeSettings} from '../settings/settings.js';import {commands} from '../commands/commands.js';
const $=s=>document.querySelector(s), repo=new ProjectRepository(),execute=new ExecutionService();let projects=[],project,active,dirty=false,settings,terminalOpen=true, explorerOpen=true,previewHtml='';
const toast=(message,type='info')=>{const el=$('#toast');el.textContent=message;el.className='toast '+type;setTimeout(()=>el.className='toast',3500)};
async function boot(){settings=mergeSettings(await repo.settings());projects=await repo.list();if(!projects.length){project=fromTemplate('web','My first project');await repo.save(project);projects=[project]}else project=projects[0];active=project.files[0]?.path;render()}
function tree(){let dirs=new Set(project.directories);project.files.forEach(f=>{let p=parentPath(f.path);while(p){dirs.add(p);p=parentPath(p)}});const children=(base='')=>[...dirs].filter(d=>parentPath(d)===base).sort().map(d=>`<div class="tree-dir"><div class="tree-row folder" data-path="${d}">⌄ <span>📁 ${d.split('/').pop()}</span><button data-action="manage" data-path="${d}">⋯</button></div>${children(d)}</div>`).join('')+[...project.files].filter(f=>parentPath(f.path)===base).sort((a,b)=>a.path.localeCompare(b.path)).map(f=>`<div class="tree-row file ${active===f.path?'selected':''}" data-open="${f.path}"><span>${icon(f.path)} ${f.path.split('/').pop()}</span><button data-action="manage" data-path="${f.path}">⋯</button></div>`).join('');return children()}
function icon(p){return p.endsWith('.html')?'◇':p.endsWith('.css')?'#':p.endsWith('.js')?'JS':p.endsWith('.json')?'{}':'•'}
function render(){document.documentElement.style.setProperty('--font-size',settings.fontSize+'px');$('#app').innerHTML=`<header><div class="brand">◈ <b>Forge</b><span>IDE</span></div><select id="projectSelect">${projects.map(p=>`<option value="${p.id}" ${p.id===project.id?'selected':''}>${p.name}</option>`).join('')}</select><button id="newProject">＋ Project</button><div class="head-actions"><button id="save">Save</button><button class="run" id="run">▶ Run</button><button id="palette">⌘ P</button><button id="settings">⚙</button></div></header><main class="${explorerOpen?'':'no-explorer'}"><aside class="explorer"><div class="panel-title">EXPLORER <span><button id="newFile">＋</button><button id="newFolder">□</button><button id="import">⇧</button></span></div><div class="root">${project.name}</div><nav id="tree">${tree()}</nav><div class="explorer-footer"><button id="export">⇩ Export</button><button id="deleteProject">Delete project</button></div></aside><section class="work"><div class="tabs">${active?`<div class="tab active">${active.split('/').pop()}${dirty?' ●':''}<button id="closeTab">×</button></div>`:'<div class="tab">No file open</div>'}</div><div class="editor-wrap">${active?`<div class="gutter"></div><textarea id="editor" spellcheck="false" aria-label="Code editor">${escape(project.files.find(f=>f.path===active)?.content||'')}</textarea>`:'<div class="empty">Select a file to start editing</div>'}</div></section><aside class="preview"><div class="panel-title">PREVIEW <span><button id="refresh">↻</button><button id="openPreview">↗</button></span></div><div class="device"><iframe id="previewFrame" sandbox="allow-scripts"></iframe></div><div class="preview-note">Web preview runs in an isolated iframe.</div></aside></main><section class="terminal ${terminalOpen?'':'hidden'}"><div class="terminal-head"><span>TERMINAL</span><span><button id="clearTerminal">Clear</button><button id="toggleTerminal">×</button></span></div><pre id="output">Ready. Create or open an HTML project, then press Run.</pre></section><footer><span>◉ ${dirty?'Unsaved changes':'Saved'}</span><span>${active||'No file'} · UTF-8</span><span>Spaces: ${settings.tabSize} · ${settings.wordWrap?'Wrap':'No wrap'}</span></footer><div id="modal"></div><div id="toast" class="toast"></div><input id="fileInput" type="file" accept=".json,.forge-project.json" hidden></div>`;bind();updatePreview()}
const escape=s=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;');
function bind(){document.addEventListener('keydown',keys);$('#tree').onclick=e=>{const p=e.target.closest('[data-open]')?.dataset.open;if(p){active=p;dirty=false;render();return}const r=e.target.closest('[data-action=manage]');if(r)manage(r.dataset.path)};$('#editor')?.addEventListener('input',e=>{project.files.find(f=>f.path===active).content=e.target.value;dirty=true;if(settings.autoSave)save()});$('#save').onclick=save;$('#run').onclick=run;$('#newFile').onclick=()=>add(false);$('#newFolder').onclick=()=>add(true);$('#newProject').onclick=newProject;$('#projectSelect').onchange=async e=>{project=await repo.get(e.target.value);active=project.files[0]?.path;dirty=false;render()};$('#deleteProject').onclick=deleteProject;$('#export').onclick=()=>exportProject(project);$('#import').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=async e=>{try{project=await importProject(e.target.files[0]);await save();projects=await repo.list();active=project.files[0]?.path;render();toast('Project imported.','success')}catch(x){toast(x.message,'error')}};$('#clearTerminal').onclick=()=>$('#output').textContent='';$('#toggleTerminal').onclick=()=>{terminalOpen=false;render()};$('#refresh').onclick=run;$('#openPreview').onclick=()=>{const w=window.open();w.document.write(previewHtml||'<p>Run a web project first.</p>')};$('#palette').onclick=palette;$('#settings').onclick=settingsModal;$('#closeTab')?.addEventListener('click',()=>{active=null;render()})}
async function save(){try{touch(project);await repo.save(project);projects=await repo.list();dirty=false;render();toast('Project saved.','success')}catch(e){toast(e.message,'error')}}
function add(folder){const path=prompt(folder?'Folder path (example: src/components)':'File path (example: src/main.js)');if(!path)return;try{folder?createDirectory(project,path):createFile(project,path,'');active=folder?active:path;dirty=true;save()}catch(e){toast(e.message,'error')}}
function manage(path){const choice=prompt('Type r to rename/move or d to delete:', 'r');if(choice?.toLowerCase()==='d'){if(confirm(`Delete ${path}?`)){try{removeEntry(project,path);if(active===path)active=null;save()}catch(e){toast(e.message,'error')}};return}if(choice?.toLowerCase()==='r')rename(path)}
function rename(path){const dest=prompt('Rename or move to:',path);if(!dest||dest===path)return;try{renameEntry(project,path,dest);if(active===path)active=dest;save()}catch(e){toast(e.message,'error')}}
async function deleteProject(){if(!confirm(`Delete ${project.name}?`))return;await repo.delete(project.id);projects=await repo.list();if(!projects.length){project=createProject('Untitled project');createFile(project,'index.html','<h1>New project</h1>');await repo.save(project);projects=[project]}project=projects[0];active=project.files[0]?.path;render()}
async function newProject(){const name=prompt('Project name','New project');if(!name)return;const kind=prompt('Template: web, typescript, react, python, kotlin','web');project=fromTemplate(kind,name);await save();projects=await repo.list();active=project.files[0]?.path;render()}
async function run(){const o=$('#output');terminalOpen=true;render();const out=$('#output');out.textContent='Running…\n';try{const r=await execute.run(project,(kind,msg)=>out.textContent+=`[${kind}] ${msg}\n`);previewHtml=r.html||previewHtml;out.textContent+=`\nProcess finished with exit code ${r.exitCode} in ${Math.round(r.duration)}ms`;updatePreview();toast('Run completed.','success')}catch(e){out.textContent+=`\n[stderr] ${e.message}\nProcess failed.`;toast(e.message,'error')}}
function updatePreview(){const f=$('#previewFrame');if(f&&previewHtml)f.srcdoc=previewHtml}
function palette(){const acts={newFile:()=>add(false),newFolder:()=>add(true),save,run,toggleTerminal:()=>{terminalOpen=!terminalOpen;render()},toggleExplorer:()=>{explorerOpen=!explorerOpen;render()},export:()=>exportProject(project),import:()=>$('#fileInput').click(),preview:()=>$('#openPreview').click()};const list=commands(acts);modal(`<h2>Command Palette</h2><input id="commandSearch" autofocus placeholder="Type a command…"><div id="commandList">${list.map(c=>`<button data-command="${c.id}">${c.label}<kbd>${c.shortcut||''}</kbd></button>`).join('')}</div>`);$('#commandList').onclick=e=>{const c=list.find(x=>x.id===e.target.closest('button')?.dataset.command);if(c){closeModal();c.run()}};$('#commandSearch').oninput=e=>document.querySelectorAll('#commandList button').forEach(b=>b.hidden=!b.textContent.toLowerCase().includes(e.target.value.toLowerCase()))}
function settingsModal(){modal(`<h2>IDE Settings</h2><label>Font size <input id="font" type="range" min="12" max="20" value="${settings.fontSize}"></label><label>Tab size <select id="tabsize"><option>2</option><option>4</option></select></label><label><input id="wrap" type="checkbox" ${settings.wordWrap?'checked':''}> Word wrap</label><label><input id="autosave" type="checkbox" ${settings.autoSave?'checked':''}> Auto-save</label><button id="settingsSave" class="run">Save settings</button>`);$('#tabsize').value=settings.tabSize;$('#settingsSave').onclick=async()=>{settings={...settings,fontSize:+$('#font').value,tabSize:+$('#tabsize').value,wordWrap:$('#wrap').checked,autoSave:$('#autosave').checked};await repo.saveSettings(settings);closeModal();render()}}
function modal(content){$('#modal').innerHTML=`<div class="backdrop"></div><div class="dialog">${content}<button class="close">×</button></div>`;$('.backdrop').onclick=closeModal;$('.close').onclick=closeModal}function closeModal(){$('#modal').innerHTML=''}
function keys(e){if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();save()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='p'){e.preventDefault();palette()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='b'){e.preventDefault();explorerOpen=!explorerOpen;render()}if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();run()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='w'){e.preventDefault();active=null;render()}}
boot().catch(e=>document.body.innerHTML=`<pre>Forge failed to start: ${e.message}</pre>`);
